USE auto_contract;
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (1, 'Гайсинські', 'ГА', '23700, Вінницька обл., Гайсинський р-н., м.Гайсин, вул. І. Богуна, 122', 1);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (2, 'Теплицькі', 'ТЕ', '23800, Вінницька обл., Гайсинський р-н., смт.Теплик, вул. Енергетиків, 11', 1);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (3, 'Тростянецькі', 'ТР', '24300, Вінницька обл., смт. Тростянець, вул. Соборна, 98', 1);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (4, 'Чечельницькі', 'ЧЧ', '24800, Вінницька обл.,Гайсинський р-н, смт. Чечельник, вул. Антонішина, 62', 1);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (5, 'Бершадські', 'БЕ', '24400, Вінницька обл., Гайсинський р-н, м. Бершадь, вул. Шевченка, 24', 1);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (6, 'Вінницькі', 'ВІ', '21000, Вінницька обл., м. Вінниця, вул. Пирогова, 174', 2);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (7, 'Замостянські', 'ЗА', '21008, Вінницька обл., м. Вінниця, вул. Гніванське шосе, 1', 3);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (8, 'Літинські', 'ЛІ', '22300, Вінницька обл., смт Літин, вул. Вінницька, 66', 3);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (9, 'Тиврівські', 'ТИ', '22300, Вінницька обл., смт. Тиврів, вул. Грушевського, 6', 3);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (10, 'Іллінецькі', 'ІЛ', '22700, Вінницька обл., м. Іллінці, вул. Європейська, буд.33', 4);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (11, 'Немирівські', 'НЕ', '22800, Вінницька обл., м. Немирів, вул. Горького, 2', 4);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (12, 'Оратівські', 'ОР', '22600, Вінницька обл., смт Оратів, вул. Паркова, 15', 4);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (13, 'Погребищенські', 'ПО', '22200, Вінницька обл., Вінницький р-н, р-н, м. Погребище, вул. Коцюбинського, 23', 4);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (14, 'Липовецькі', 'ЛИ', '22500, Вінницька область, м. Липовець, вул. Некрасова, 10', 4);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (15, 'Могилів-Подільські', 'МО', '24000, Вінницька обл., м. Могилів-Подільський, вул. Полтавська, 87', 8);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (16, 'Муровано-Курилівецькі', 'МУ', '23400, Вінницька обл., смт. Муровані Курилівці, вул. Гагаріна, 51', 8);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (17, 'Чернівецькі', 'ЧЕ', '24100, Вінницька обл., смт. Чернівці, вул. Святомиколаївська, 1', 8);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (18, 'Ямпільські', 'ЯМ', '24500, Вінницька обл., м. Ямпіль, вул. Свободи, 5', 8);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (19, 'Тульчинські', 'ТУ', '23600, Вінницька обл., м. Тульчин, вул. Пушкіна, 1А', 7);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (20, 'Томашпільські', 'ТО', '24200, Вінницька обл., Томашпільський р-н, с. Яришівка, вул. Нова, 30', 7);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (21, 'Піщанські', 'ПІ', '24700, Вінницька обл., Тульчинський р-н., смт. Піщанка, вул. Центральна, 133', 7);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (22, 'Крижопільські', 'КР', '24600, Вінницька обл., Тульчинський р-н, смт. Крижопіль, вул. Залізної дивізії,81', 7);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (23, 'Жмеринські', 'ЖМ', '23100, Вінницька обл., м. Жмеринка, вул. Асмолова,10', 6);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (24, 'Шаргородські', 'ША', '23500, Вінницька обл., м. Шаргород, вул. Героїв Майдану, 308', 6);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (25, 'Барські', 'БА', '23006, Вінницька обл., Жмеринський р-н, с. Балки, вул. Заводська, 4', 6);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (26, 'Хмільницькі', 'ХМ', '22000, Вінницька обл., м. Хмільник, вул. Столярчука, буд. 19', 5);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (27, 'Козятинські', 'КО', '22145, Вінницька обл., Хмільницький р-н, с.Сигнал, вул.Ярослава Мудрого, буд.172', 5);
INSERT INTO pages_department (id, department, code, address, so_id) VALUES (28, 'Калинівські', 'КА', '22400, Вінницька обл., м.Калинівка, вул. Промислова, 16', 5);
