# Generated by Django 4.2.3 on 2023-09-14 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='So',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('document_num', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Назви СО',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('schema', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('tp_num', models.CharField(blank=True, default='', max_length=20, verbose_name='Номер ТП')),
                ('line_num', models.CharField(blank=True, default='', max_length=20, verbose_name='Номер лінії')),
                ('fider_num', models.CharField(blank=True, default='', max_length=20, verbose_name='Номер фідера')),
                ('fider_type', models.CharField(blank=True, default='', max_length=10, verbose_name='Тип фідера')),
                ('resistance_num', models.CharField(blank=True, default='', max_length=10, verbose_name='Номер опори')),
                ('full_trans_power', models.CharField(blank=True, default='', max_length=20, verbose_name='Повна потужність трансформатора')),
                ('substation_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Назва підстанції')),
                ('line_type', models.CharField(blank=True, default='', max_length=20, verbose_name='Тип лінії')),
                ('line_length', models.CharField(blank=True, default='', max_length=20, verbose_name='Довжина лінії')),
                ('active_line_resistance', models.CharField(blank=True, default='', max_length=20, verbose_name='Активний опір лінії')),
                ('reactive_line_resistance', models.CharField(blank=True, default='', max_length=20, verbose_name='Реактивний опір лінії')),
                ('power', models.CharField(blank=True, default='', max_length=20, verbose_name='Потужність')),
                ('work_mode', models.CharField(blank=True, default='', max_length=20, verbose_name='Режим роботи')),
                ('voltage_level', models.CharField(blank=True, default='', max_length=20, verbose_name='Ступінь напруги ТРЕЕ')),
                ('shield', models.CharField(blank=True, default='', max_length=20, verbose_name='Щитова')),
                ('stream_av', models.CharField(blank=True, default='', max_length=20, verbose_name='Струм АВ')),
                ('line_mark', models.CharField(blank=True, default='', max_length=100, verbose_name='Марка лінії')),
                ('section_numbers', models.CharField(blank=True, default='', max_length=100, verbose_name='Кількість х Переріз')),
                ('initial_indicators', models.CharField(blank=True, default='', max_length=100, verbose_name='Початкові показники')),
                ('counter_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Тип лічильника')),
                ('counter_serial_num', models.CharField(blank=True, default='', max_length=100, verbose_name='Серійний номер лічильника')),
                ('counter_nominal', models.CharField(blank=True, default='', max_length=100, verbose_name='Номінал лічильника')),
                ('quarter', models.CharField(blank=True, default='', max_length=100, verbose_name='Квартал та рік повірки')),
                ('reliability_category', models.CharField(blank=True, default='', max_length=100, verbose_name='Категорія надійності струмоприймачів')),
                ('av_stream_ru_04', models.CharField(blank=True, default='', max_length=100, verbose_name='Струм АВ в РУ-0,4кВ')),
                ('full_power_t1', models.CharField(blank=True, default='', max_length=100, verbose_name='Повна потужність Т1')),
                ('full_power_t2', models.CharField(blank=True, default='', max_length=100, verbose_name='Повна потужність Т2')),
                ('os_section_numbers', models.CharField(blank=True, default='', max_length=100, verbose_name='Кількість Х Переріз ліній на балансі ОС')),
                ('os_line_mark', models.CharField(blank=True, default='', max_length=100, verbose_name='Марка лінії на балансі ОС')),
                ('os_line_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Тип лінії на балансі ОС')),
                ('os_line_length', models.CharField(blank=True, default='', max_length=100, verbose_name='Довжина лінії на балансі ОС')),
                ('cutter_num_VRSH', models.CharField(blank=True, default='', max_length=100, verbose_name='Номінал рубільника в ВРЩ ж/б')),
                ('auth_person_position', models.CharField(blank=True, default='', max_length=100, verbose_name='Посада\nуповноваженої особи')),
                ('object_type', models.CharField(blank=True, default='', max_length=100, verbose_name="Вид об'єкта")),
                ('contract_num', models.CharField(blank=True, default='', max_length=100, verbose_name='Номер договору')),
                ('eis_code', models.CharField(blank=True, default='', max_length=100, verbose_name='ЕІС-код')),
                ('position_pib', models.CharField(blank=True, default='', max_length=100, verbose_name='Посада уповноваженої особи споживача, П.І.Б.')),
                ('full_cons_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Повна юр. назва споживача')),
                ('activity_document', models.CharField(blank=True, default='', max_length=100, verbose_name='Документ за яким споживач здійснює діяльність')),
                ('abbreviated_full_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Скорочена повна юр. назва споживача')),
                ('consumer_pib', models.CharField(blank=True, default='', max_length=100, verbose_name='П.І.Б. споживача')),
                ('index_legal_address', models.CharField(blank=True, default='', max_length=100, verbose_name='Індекс, Юридична адреса')),
                ('index_circulation_address', models.CharField(blank=True, default='', max_length=100, verbose_name='Індекс, Адреса для документообігу')),
                ('actual_address', models.CharField(blank=True, default='', max_length=100, verbose_name="Фактична адреса об'єкту")),
                ('av_num', models.CharField(blank=True, default='', max_length=100, verbose_name='Номінал АВ')),
                ('av_num_vrs', models.CharField(blank=True, default='', max_length=100, verbose_name='Номінал АВ в ВРЩ ж/б')),
                ('general_consumer_pib', models.CharField(blank=True, default='', max_length=100, verbose_name='П.І.Б. основного споживача')),
                ('general_consumer_abbreviated', models.CharField(blank=True, default='', max_length=100, verbose_name='Скорочена повна юр. назва основного споживача')),
                ('general_full_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Повна юр. назва основного споживача')),
                ('consumer_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.consumercategory')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.department')),
                ('so', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.so')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='so',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.so'),
        ),
    ]
