# Generated by Django 4.2.3 on 2023-09-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumercategory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
