# Generated by Django 4.2.3 on 2023-10-17 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_consumercategory_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='consumer_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.consumercategory'),
        ),
    ]
